const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const footballerSchema = new Schema({
    Name:String,
    Nationality:String,
    National_Position:String,
    National_Kit: String,
    Club: String,
    Club_Position: String,
    Club_Kit: String,
    Club_Joining: Date,
    Contract_Expiry: Date,
    Rating: Number,
    Height: String,
    Weight: String,
    Preffered_Foot: String,
    Birth_Date: Date,
    Age: Number,
    Preffered_Position: String,
    Work_Rate: String,
    Weak_foot: Number,
    Skill_Moves: Number,
    Ball_Control: Number,
    Dribbling: Number,
    Marking: Number,
    Sliding_Tackle: Number,
    Standing_Tackle: Number,
    Aggression: Number,
    Reactions: Number,
    Attacking_Position: Number,
    Interceptions: Number,
    Vision: Number,
    Composure: Number,
    Crossing: Number,
    Short_Pass: Number,
    Long_Pass: Number,
    Acceleration: Number,
    Speed: Number,
    Stamina: Number,
    Strength: Number,
    Balance: Number,
    Agility: Number,
    Jumping: Number,
    Heading: Number,
    Shot_Power: Number,
    Finishing: Number,
    Long_Shots: Number,
    Curve: Number,
    Freekick_Accuracy: Number,
    Penalties: Number,
    Volleys: Number,
    GK_Positioning: Number,
    GK_Diving: Number,
    GK_Kicking: Number,
    GK_Handling: Number,
    GK_Reflexes: Number
})

const Footballer = mongoose.model('footballers', footballerSchema);

module.exports = Footballer;